QUANTIFIABLE_COLUMNS = {
    "Offers Nursing Care Services",
    "Offers Physical Therapy Services",
    "Offers Occupational Therapy Services",
    "Offers Speech Pathology Services",
    "Offers Medical Social Services",
    "Offers Home Health Aide Services",
    "Certification Date",
    "Quality of patient care star rating",
    "How often the home health team began their patients' care in a timely manner",
    "How often the home health team determined whether patients received a flu shot for the current flu season",
    "How often patients got better at walking or moving around",
    "How often patients got better at getting in and out of bed",
    "How often patients got better at bathing",
    "How often patients' breathing improved",
    "How often patients got better at taking their drugs correctly by mouth",
    "How often home health patients had to be admitted to the hospital",
    "How often patients receiving home health care needed urgent, unplanned care in the ER without being admitted",
    "Changes in skin integrity post-acute care: pressure ulcer/injury",
    "How often physician-recommended actions to address medication issues were completely timely",
    "Percent of Residents Experiencing One or More Falls with Major Injury",
    "Application of Percent of Long Term Care Hospital Patients with an Admission and Discharge Functional Assessment and a Care Plan that Addresses Function",
    "DTC Numerator",
    "DTC Denominator",
    "DTC Observed Rate",
    "DTC Risk-Standardized Rate",
    "DTC Risk-Standardized Rate (Lower Limit)",
    "DTC Risk-Standardized Rate (Upper Limit)",
    "PPR Numerator",
    "PPR Denominator",
    "PPR Observed Rate",
    "PPR Risk-Standardized Rate",
    "PPR Risk-Standardized Rate (Lower Limit)",
    "PPR Risk-Standardized Rate (Upper Limit)",
    "PPH Numerator",
    "PPH Denominator",
    "PPH Observed Rate",
    "PPH Risk-Standardized Rate",
    "PPH Risk-Standardized Rate (Lower Limit)",
    "PPH Risk-Standardized Rate (Upper Limit)",
    "How much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally",
    "No. of episodes to calc how much Medicare spends per episode of care at agency, compared to spending at all agencies (national)"
}
